server.port: 9999

app.eureka-server: localhost

spring.application.name: auth

spring.jpa.hibernate.ddl-auto: update

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bootex
    username: bootuser
    password: bootuser

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
    reigster-with-eureka: true
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

ribbon.ServerListRefreshInterval: 5000
ribbon.NFLoadBalancerPingInterval: 5

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---

spring.profiles: docker

app.eureka-server: eureka

spring.datasource:
  url: jdbc:mysql://mysql/spreadmat
  username: user
  password: pwd
