server.port: 8080

spring.application.name: gateway

app.eureka-server: localhost
app.auth-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
    reigster-with-eureka: true
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

ribbon.ServerListRefreshInterval: 5000
ribbon.NFLoadBalancerPingInterval: 5

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

spring.cloud.gateway.routes:

- id: vendor
  uri: lb://vendor
  predicates: #이게 붙으면 앞에 있는 호스트를 위에로 연결시켜주겠다 이 말이여
  - Path=/vendor/**

- id: qna
  uri: lb://qna
  predicates:
    - Path=/qna/**

- id: auth
  uri: lb://auth
  predicates:
  - Path=/oauth/**


- id: member
  uri: lb://auth
  predicates:
    - Path=/member/**

- id: chat-message
  uri: lb://chat
  predicates:
    - Path=/message/**

- id: chat-history
  uri: lb://chat
  predicates:
    - Path=/history/**

- id: chatroom
  uri: lb://chat
  predicates:
    - Path=/chatroom/**

- id: chatroom-sockjs-route
  uri: http://chat:8080
  predicates:
    - Path=/chatting/info/**

- id: chat-websocket
  uri: lb:ws://chat:8080
  predicates:
    - Path=/chatting/**

- id: eureka-api
  uri: http://${app.eureka-server}:8761
  predicates:
  - Path=/eureka/api/{segment}
  filters:
  - SetPath=/eureka/{segment}

- id: eureka
  uri: http://${app.eureka-server}:8761
  predicates:
  - Path=/eureka
  filters:
  - SetPath=/

spring.cloud.gateway.globalcors:
  cors-configurations:
    '[/**]':
      allowedOrigins: "http://localhost"
      allow-credentials: true
      allowedHeaders:
        - x-requested-with
        - authorization
        - content-type
        - credential
        - X-AUTH-TOKEN
        - X-CSRF-TOKEN
      allowedMethods:
        - POST
        - GET
        - PUT
        - OPTIONS
        - DELETE

spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://${app.auth-server}:9999/.well-known/jwks.json


---

spring.profiles: docker

app.eureka-server: eureka
app.auth-server: auth


